@Echo off 
echo.
cls
echo     LOADING...
echo ==================
echo .
echo ==================
echo     please wait... 
ping localhost -n 2 >nul
cls
echo    LOADING...
echo ==================
echo ..
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo     LOADING...
echo ==================
echo ....
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo    LOADING...
echo ==================
echo ......
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo     LOADING...
echo ==================
echo ........
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo    LOADING...
echo ==================
echo ..........
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo     LOADING...
echo ==================
echo ............
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo    LOADING...
echo ==================
echo ..............
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo     LOADING...
echo ==================
echo ................
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo    LOADING...
echo ==================
echo ..................
echo ==================
echo     please wait...
ping localhost -n 2 >nul
cls
echo ==================
echo     CONNECTED.
echo ==================
pause 
echo.